"""initial

Revision ID: 9027d416ea65
Revises: 
Create Date: 2022-09-26 23:21:36.507230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9027d416ea65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('artist', 'user', name='account_type_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default='server', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), server_default='server', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index('idx_account_source_id', 'account', ['source_id'], unique=False)
    op.create_table('follower',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('follower_id', sa.String(), nullable=False),
    sa.Column('following_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), server_default='server', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), server_default='server', nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['account.source_id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['account.source_id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_index(op.f('ix_follower_follower_id'), 'follower', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follower_following_id'), 'follower', ['following_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follower_following_id'), table_name='follower')
    op.drop_index(op.f('ix_follower_follower_id'), table_name='follower')
    op.drop_table('follower')
    op.drop_index('idx_account_source_id', table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
