"""add source id constraint

Revision ID: 9b435f4a8743
Revises: f5142cfa8392
Create Date: 2022-09-11 21:24:24.977097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b435f4a8743'
down_revision = 'f5142cfa8392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'source_id',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('account', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('account', 'type',
                    existing_type=postgresql.ENUM(
                        'artist', 'user', name='account_type_enum'),
                    nullable=False)
    # op.drop_index('ix_account_source_id', table_name='account')
    op.create_index('idx_account_source_id', 'account',
                    ['source_id'], unique=True)
    op.create_unique_constraint(None, 'account', ['source_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_index('idx_account_source_id', table_name='account')
    op.create_index('ix_account_source_id', 'account',
                    ['source_id'], unique=False)
    op.alter_column('account', 'type',
                    existing_type=postgresql.ENUM(
                        'artist', 'user', name='account_type_enum'),
                    nullable=True)
    op.alter_column('account', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('account', 'source_id',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # sa.Enum('artist', 'user', name='account_type_enum', ).drop(op.get_bind())

    # ### end Alembic commands ###
