"""change primary key of follow to be follower and folling ids

Revision ID: a1822833f785
Revises: 9b435f4a8743
Create Date: 2022-09-16 23:03:54.367900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1822833f785'
down_revision = '9b435f4a8743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_source_id', table_name='account')
    op.drop_index('idx_account_source_id', table_name='account')
    op.create_index('idx_account_source_id', 'account',
                    ['source_id'], unique=False)
    op.drop_constraint(constraint_name='follower_pkey', table_name='follower')
    op.alter_column('follower', 'id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('follower', 'follower_id',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('follower', 'following_id',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follower', 'following_id',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('follower', 'follower_id',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('follower', 'id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_index('idx_account_source_id', table_name='account')
    op.create_index('idx_account_source_id', 'account',
                    ['source_id'], unique=False)
    op.create_index('ix_account_source_id', 'account',
                    ['source_id'], unique=False)
    # ### end Alembic commands ###
