"""add created and updated columns

Revision ID: b49d1e7c81e5
Revises: a1822833f785
Create Date: 2022-09-26 20:26:09.887903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49d1e7c81e5'
down_revision = 'a1822833f785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('account', sa.Column('created_by', sa.String(), server_default='server', nullable=False))
    op.add_column('account', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('account', sa.Column('updated_by', sa.String(), server_default='server', nullable=False))
    op.add_column('follower', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('follower', sa.Column('created_by', sa.String(), server_default='server', nullable=False))
    op.add_column('follower', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('follower', sa.Column('updated_by', sa.String(), server_default='server', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follower', 'updated_by')
    op.drop_column('follower', 'updated_at')
    op.drop_column('follower', 'created_by')
    op.drop_column('follower', 'created_at')
    op.drop_column('account', 'updated_by')
    op.drop_column('account', 'updated_at')
    op.drop_column('account', 'created_by')
    op.drop_column('account', 'created_at')
    # ### end Alembic commands ###
